[package]
name = "substrate-subxt"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "GPL-3.0"
readme = "README.md"
description = "Submit extrinsics (transactions) to a substrate node via RPC"
keywords = ["parity", "substrate", "blockchain"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
hex = "0.4.0"
log = "0.4"
thiserror = "1.0"
futures = "0.3"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee/", features = ["ws"] }
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "1.7"
codec = { package = "parity-scale-codec", version = "1.2", default-features = false, features = ["derive", "full"] }

frame-metadata = { version = "11.0.0-alpha.3", package = "frame-metadata" }

[dependencies.frame-support]
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dependencies.sp-version]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dependencies.pallet-indices]
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dependencies.sp-rpc]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-rpc'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-transaction-pool'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dev-dependencies]
async-std = "1.2.0"
env_logger = "0.7"
wabt = "0.9"

[dev-dependencies.frame-system]
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dev-dependencies.pallet-balances]
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'

[dev-dependencies.sp-keyring]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-keyring'
rev = '013c1ee167354a08283fb69915fda56a62fee943'
version = '2.0.0-alpha.3'
